version: "3"

# volumes:
#   database:
#     driver: local

networks:
  webnet:
volumes:
  pgdata:


services:
  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres-kcp
    # command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB'
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8' COMMENTED OUT AS prisma db:migrate is failing (maybe since pg 15 ??)
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PG_DATA: /var/lib/postgresql/data_kcp
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data_kcp
