name: Run Pytest on Pull Requests

on:
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: cache poetry install
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-1.7.1

    - uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: cache deps
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: .venv
        key: pydeps-${{ hashFiles('**/poetry.lock') }}

    - run: poetry install --no-interaction --no-root
      if: steps.cache-deps.outputs.cache-hit != 'true'

    - name: Install dependencies using Poetry
      run: |
        poetry install --no-interaction

    - name: Setup Prisma Client
      run: |
        poetry run prisma generate --schema=packages/database/prisma/schema.prisma

    - name: Run Pytest
      run: poetry run pytest
